spring:
  application:
    name: spring-grpc-client
server:
  port: 8081
grpc:
  server:
    port: 9091
  client:
    local-grpc-server:
      address: 'static://localhost:9090'
      negotiation-type: plaintext